@accessToken = {{login.response.body.access_token}}
@battleID = {{create_battle.response.body.id}}

# Login

# @name login
POST http://localhost:3007/login
Content-Type: application/x-www-form-urlencoded

&username=admin
&password=admin

###

# Create Battle

# @name create_battle
POST http://localhost:3007/battle
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

{
    "base_layout_data": "qwertyuiopasdfghjkl;'zxcvbnm,./",
    "is_personal": false
}

###

# Get Battle

GET http://localhost:3007/battle/{{battleID}}
Authorization: Bearer {{accessToken}}

###

# Finalize Battle

PUT http://localhost:3007/battle
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

{
    "id": "{{battleID}}",
    "times": [
        [1000, 1000],
        [1100, 1000],
        [1000, 1100],
        [1300, 1100],
        [1000, 1400]
    ],
    "comfort_choice": [
        1,
        2,
        1,
        0,
        2
    ]
}

###